//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSorrySliders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseDeDatosSorrySlidersEntities : DbContext
    {
        public BaseDeDatosSorrySlidersEntities()
            : base("name=BaseDeDatosSorrySlidersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CuentaSet> CuentaSet { get; set; }
        public virtual DbSet<NotificaciónSet> NotificaciónSet { get; set; }
        public virtual DbSet<PartidaSet> PartidaSet { get; set; }
        public virtual DbSet<RelaciónAmigosSet> RelaciónAmigosSet { get; set; }
        public virtual DbSet<RelacionBaneadosSet> RelacionBaneadosSet { get; set; }
        public virtual DbSet<RelacionPartidaCuentaSet> RelacionPartidaCuentaSet { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSet { get; set; }
    }
}
