//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSorrySliders
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class NotificacionSet
    {
        [DataMember]
        public int IdNotificacion { get; set; }
        [DataMember]
        public string CorreoElectronicoRemitente { get; set; }
        [DataMember]
        public string CorreoElectronicoDestinatario { get; set; }
        [DataMember]
        public Nullable<int> IdTipoNotificacion { get; set; }
        [DataMember]
        public string Mensaje { get; set; }
        [DataMember]
        public virtual CuentaSet CuentaSet { get; set; }
        [DataMember]
        public virtual CuentaSet CuentaSet1 { get; set; }
        [DataMember]
        public virtual TipoNotificacion TipoNotificacion { get; set; }
    }
}
