//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSorrySliders
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionPartidaCuentaSet
    {
        public int IdPartidaCuenta { get; set; }
        public int Posicion { get; set; }
        public System.Guid CodigoPartida { get; set; }
        public string CorreoElectronico { get; set; }
    
        public virtual CuentaSet CuentaSet { get; set; }
        public virtual PartidaSet PartidaSet { get; set; }
    }
}
