//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSorrySliders
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelaciónAmigosSet
    {
        public int IdRelaciónAmigos { get; set; }
        public string CorreoElectronicoJugadorPrincipal { get; set; }
        public string CorreoElectronicoJugadorAmigo { get; set; }
    
        public virtual CuentaSet CuentaSet { get; set; }
        public virtual CuentaSet CuentaSet1 { get; set; }
    }
}
