//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosSorrySliders
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class RelacionPartidaCuentaSet
    {
        [DataMember]
        public int IdPartidaCuenta { get; set; }
        [DataMember]
        public int Posicion { get; set; }
        [DataMember]
        public System.Guid CodigoPartida { get; set; }
        [DataMember]
        public string CorreoElectronico { get; set; }
        [DataMember]
        public virtual CuentaSet CuentaSet { get; set; }
        [DataMember]
        public virtual PartidaSet PartidaSet { get; set; }
    }
}
